SELECT
    TP_USUARIO,
    LENGTH(DS_SENHA_HASH) AS TAMANHO,
    CASE
        WHEN REGEXP_LIKE(DS_SENHA_HASH, '^[0-9A-Fa-f]{32}$')
            THEN 'POSSIVEL_MD5'
        WHEN REGEXP_LIKE(DS_SENHA_HASH, '^[0-9A-Fa-f]{40}$')
            THEN 'POSSIVEL_SHA1'
        WHEN REGEXP_LIKE(DS_SENHA_HASH, '^[0-9A-Fa-f]{64}$')
            THEN 'POSSIVEL_SHA256'
        WHEN LENGTH(DS_SENHA_HASH) = 60
            THEN '60_CARACTERES_NAO_BCRYPT_PADRAO'
        ELSE 'OUTRO'
        END AS PADRAO,
    COUNT(*) AS TOTAL
FROM TB_ARKIVE_USUARIO
GROUP BY
    TP_USUARIO,
    LENGTH(DS_SENHA_HASH),
    CASE
        WHEN REGEXP_LIKE(DS_SENHA_HASH, '^[0-9A-Fa-f]{32}$')
            THEN 'POSSIVEL_MD5'
        WHEN REGEXP_LIKE(DS_SENHA_HASH, '^[0-9A-Fa-f]{40}$')
            THEN 'POSSIVEL_SHA1'
        WHEN REGEXP_LIKE(DS_SENHA_HASH, '^[0-9A-Fa-f]{64}$')
            THEN 'POSSIVEL_SHA256'
        WHEN LENGTH(DS_SENHA_HASH) = 60
            THEN '60_CARACTERES_NAO_BCRYPT_PADRAO'
        ELSE 'OUTRO'
        END
ORDER BY TP_USUARIO, TAMANHO;