SELECT
    ID_CONSULTA,
    ST_STATUS,
    DBMS_LOB.SUBSTR(DS_MOTIVO, 1000, 1) AS MOTIVO,
    DBMS_LOB.SUBSTR(DS_SINTOMAS, 1000, 1) AS SINTOMAS,
    DBMS_LOB.SUBSTR(DS_OBSERVACAO, 1000, 1) AS OBSERVACAO,
    DBMS_LOB.SUBSTR(DS_TRANSCRICAO, 2000, 1) AS TRANSCRICAO
FROM TB_ARKIVE_CONSULTA
WHERE ID_CONSULTA IN (22, 6, 23)
ORDER BY ID_CONSULTA DESC;