ALTER TABLE TB_ARKIVE_USUARIO ADD (
    NM_USUARIO VARCHAR2(150),
    ID_CLINICA NUMBER
);

UPDATE TB_ARKIVE_USUARIO u
SET NM_USUARIO =
    CASE
        WHEN u.TP_USUARIO = 'RESPONSAVEL' THEN
            COALESCE(
                (SELECT r.NM_RESPONSAVEL
                   FROM TB_ARKIVE_RESPONSAVEL r
                  WHERE r.ID_RESPONSAVEL = u.ID_RESPONSAVEL),
                u.DS_LOGIN
            )
        WHEN u.TP_USUARIO = 'VETERINARIO' THEN
            COALESCE(
                (SELECT v.NM_VETERINARIO
                   FROM TB_ARKIVE_VETERINARIO v
                  WHERE v.ID_VETERINARIO = u.ID_VETERINARIO),
                u.DS_LOGIN
            )
        ELSE u.DS_LOGIN
    END
WHERE u.NM_USUARIO IS NULL;

ALTER TABLE TB_ARKIVE_USUARIO MODIFY (
    NM_USUARIO NOT NULL
);

ALTER TABLE TB_ARKIVE_USUARIO DROP CONSTRAINT CK_ARKIVE_USUARIO_TIPO;
ALTER TABLE TB_ARKIVE_USUARIO DROP CONSTRAINT CK_ARKIVE_USUARIO_REF;

ALTER TABLE TB_ARKIVE_USUARIO ADD CONSTRAINT CK_ARKIVE_USUARIO_TIPO
    CHECK (TP_USUARIO IN ('SYSADMIN', 'ADMIN_CLINICA', 'VETERINARIO', 'RESPONSAVEL'));

ALTER TABLE TB_ARKIVE_USUARIO ADD CONSTRAINT CK_ARKIVE_USUARIO_REF
    CHECK (
        (
            TP_USUARIO = 'SYSADMIN'
            AND ID_RESPONSAVEL IS NULL
            AND ID_VETERINARIO IS NULL
            AND ID_CLINICA IS NULL
        )
        OR
        (
            TP_USUARIO = 'ADMIN_CLINICA'
            AND ID_RESPONSAVEL IS NULL
            AND ID_VETERINARIO IS NULL
            AND ID_CLINICA IS NOT NULL
        )
        OR
        (
            TP_USUARIO = 'VETERINARIO'
            AND ID_RESPONSAVEL IS NULL
            AND ID_VETERINARIO IS NOT NULL
            AND ID_CLINICA IS NULL
        )
        OR
        (
            TP_USUARIO = 'RESPONSAVEL'
            AND ID_RESPONSAVEL IS NOT NULL
            AND ID_VETERINARIO IS NULL
            AND ID_CLINICA IS NULL
        )
    );

ALTER TABLE TB_ARKIVE_USUARIO ADD CONSTRAINT FK_USUARIO_CLINICA
    FOREIGN KEY (ID_CLINICA)
    REFERENCES TB_ARKIVE_CLINICA (ID_CLINICA);

CREATE INDEX IX_ARKIVE_USUARIO_CLINICA ON TB_ARKIVE_USUARIO (ID_CLINICA);

COMMENT ON TABLE TB_ARKIVE_USUARIO IS 'Credenciais de acesso dos perfis SYSADMIN, ADMIN_CLINICA, VETERINARIO e RESPONSAVEL.';
COMMENT ON COLUMN TB_ARKIVE_USUARIO.TP_USUARIO IS 'Perfil de usuario: SYSADMIN, ADMIN_CLINICA, VETERINARIO ou RESPONSAVEL.';
COMMENT ON COLUMN TB_ARKIVE_USUARIO.NM_USUARIO IS 'Nome de exibicao do usuario para autenticacao e administracao.';
COMMENT ON COLUMN TB_ARKIVE_USUARIO.ID_CLINICA IS 'Clinica associada ao usuario ADMIN_CLINICA; nulo para demais perfis.';
