ALTER TABLE TB_ARKIVE_USUARIO ADD (
    ST_TROCA_SENHA CHAR(1) DEFAULT 'N' NOT NULL,
    DT_ULTIMA_TROCA_SENHA DATE NULL
);

ALTER TABLE TB_ARKIVE_USUARIO ADD CONSTRAINT CK_ARKIVE_USUARIO_TROCA_SENHA
    CHECK (ST_TROCA_SENHA IN ('S', 'N'));

COMMENT ON COLUMN TB_ARKIVE_USUARIO.ST_TROCA_SENHA IS 'Indica se o usuario deve trocar a senha no proximo acesso: S ou N.';
COMMENT ON COLUMN TB_ARKIVE_USUARIO.DT_ULTIMA_TROCA_SENHA IS 'Data e hora da ultima troca de senha.';
