ALTER TABLE TB_ARKIVE_DIAGNOSTICO ADD (
    DS_FONTES_IA CLOB NULL
);

COMMENT ON COLUMN TB_ARKIVE_DIAGNOSTICO.DS_FONTES_IA IS 'Fontes consultadas pelo motor clinico externo, serializadas como JSON.';
